Tailstale/Models/Reserve.cs
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Tailstale.Models;

public partial class Reserve
{
    public int id { get; set; }
    [Display(Name = "會員")]
    public int keeper_id { get; set; }
    [Display(Name = "寵物名稱")]
    public string pet_name { get; set; }
    [Display(Name = "門市")]
    public int business_ID { get; set; }
    [Display(Name = "預約時間")]
    public DateTime time { get; set; }
    [Display(Name = "服務項目")]
    public string service_name { get; set; }
    [Display(Name = "建立日期")]
    public DateTime? created_at { get; set; }
    [Display(Name = "狀態")]
    public int? status { get; set; }

    public virtual business business { get; set; }

    public virtual keeper keeper { get; set; }

    public virtual order_status statusNavigation { get; set; }
}

Tailstale/Controllers/ReserveController.cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Threading.Tasks;
using CRUD_COREMVC;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Tailstale.Models;

namespace Tailstale.Controllers
{
    [IsLoginFilter]
    public class ReserveController : Controller
    {
        private readonly TailstaleContext _context;

        public ReserveController(TailstaleContext context)
        {
            _context = context;
        }

        // GET: Reserves
        public async Task<IActionResult> Index()
        {
            //var tailstaleContext = _context.Reserve.Include(r => r.business).Include(r => r.keeper);
            //return View(await tailstaleContext.ToListAsync());
            int? loginID = HttpContext.Session.GetInt32("loginID");
            int? loginType = HttpContext.Session.GetInt32("loginType");

            var Reserves = await _context.Reserves
            .Where(b => b.business_ID == loginID)
            .OrderByDescending(b => b.id) // 根据 ID 降序排序
            .ToListAsync();


            return View(Reserves);
        }

        [HttpPost]
        public async Task<IActionResult> Index(string time)
        {
            //var tailstaleContext = _context.Business_hours.Include(b => b.business);
            //return View(await tailstaleContext.ToListAsync());

            //if (string.IsNullOrEmpty(time))
            //{
            //    ViewData["business_ID"] = new SelectList(_context.businesses, "ID", "name");
            //    return PartialView("_ReservehourPartial", new List<Reserve>());
            //}
            int? loginID = HttpContext.Session.GetInt32("loginID");
            int? loginType = HttpContext.Session.GetInt32("loginType");

            var Reserves = await _context.Reserves
            .Where(b => b.business_ID == loginID)
            .ToListAsync();


            if (!loginID.HasValue && string.IsNullOrEmpty(time))
            {
                
                return PartialView("_ReservehourPartial", new List<Reserve>());
            }

            // 準備查詢
            IQueryable<Reserve> query = _context.Reserves
                .Include(bh => bh.business)
                .Include(bh => bh.keeper)
            .Include(bh => bh.statusNavigation);

            // 根據 id 的情況添加條件
            if (loginID.HasValue)
            {
                query = query.Where(bh => bh.business_ID == loginID);
            }

            // 根據 time 的情況添加條件
            if (!string.IsNullOrEmpty(time))
            {
                // 將 time 字符串解析為 DateTime 對象
                DateTime selectedDate;
                if (!DateTime.TryParse(time, out selectedDate))
                {
                    // 如果解析失敗，返回空的部分視圖
                   
                    return PartialView("_ReservehourPartial", new List<Reserve>());
                }
                // 只比較日期部分
                query = query.Where(bh => bh.time.Date == selectedDate.Date);
            }

            // 执行查询并返回结果
            var businessHours = await query.ToListAsync();
            
            return PartialView("_ReservehourPartial", businessHours);




        }




    




        // GET: Reserve/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reserve = await _context.Reserves
                .Include(r => r.business)
                .Include(r => r.keeper)
                .Include(bh => bh.statusNavigation)
                .FirstOrDefaultAsync(m => m.id == id);
            if (reserve == null)
            {
                return NotFound();
            }

            return View(reserve);
        }

        // GET: Reserve/Create
        public IActionResult Create()
        {
            
            var orderstatus = _context.order_statuses
               .Where(b => b.business_type_ID == 2)
               .ToList();

            int? loginID = HttpContext.Session.GetInt32("loginID");
            var businesses = _context.businesses
           .Where(b => b.ID == loginID)
           .ToList();

            var service = _context.Services
           .Where(b => b.business_ID == loginID)
           .ToList();

            ViewData["servicename"] = new SelectList(service, "service_name", "service_name");
            ViewBag.LoginID = loginID.HasValue ? loginID.Value : (int?)null;
            ViewData["business_ID"] = new SelectList(businesses, "ID", "name");
            ViewData["Orderstatus_ID"] = new SelectList(orderstatus, "ID", "status_name");
            //ViewData["business_ID"] = new SelectList(_context.businesses, "ID", "name");
            ViewData["keeper_id"] = new SelectList(_context.keepers, "ID", "name");
            return View();

        }

        // POST: Reserves/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,keeper_id,pet_name,business_ID,time,service_name,created_at,status")] ReserveViewModel reserve)
        {
            if (ModelState.IsValid)
            {
                Reserve a = new Reserve()
                {
                    keeper_id = reserve.keeper_id,
                    pet_name = reserve.pet_name,
                    business_ID = reserve.business_ID,
                    time = reserve.time,
                    service_name = reserve.service_name,
                    status = reserve.status,

                };


                _context.Add(a);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            

            var orderstatus = _context.order_statuses
                .Where(b => b.business_type_ID == 2)
                .ToList();

            int? loginID = HttpContext.Session.GetInt32("loginID");
            var businesses = _context.businesses
           .Where(b => b.ID == loginID)
           .ToList();
            var service = _context.Services
           .Where(b => b.business_ID == loginID)
           .ToList();

            ViewData["service_name"] = new SelectList(service, "service_name", "service_name");

            ViewData["business_ID"] = new SelectList(businesses, "ID", "name");

            ViewData["Orderstatus_ID"] = new SelectList(orderstatus, "ID", "status_name");

            
            //ViewData["business_ID"] = new SelectList(_context.businesses, "ID", "name", reserve.business_ID);
            //ViewData["keeper_id"] = new SelectList(_context.keepers, "ID", "address", reserve.keeper_id);
            ViewData["keeper_id"] = new SelectList(_context.keepers, "ID", "name");
            return View(reserve);
        }

        // GET: Reserves/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reserve = await _context.Reserves.FindAsync(id);
            if (reserve == null)
            {
                return NotFound();
            }
            

            var pets = _context.pets
            .Where(p => p.keeper_ID == reserve.keeper_id) // 根据 keeper_id 进行过滤
           .ToList();

            var keeper = _context.keepers
           .Where(p => p.ID == reserve.keeper_id) // 根据 keeper_id 进行过滤
          .ToList();

            var orderstatus = _context.order_statuses
               .Where(b => b.business_type_ID == 2)
               .ToList();

            int? loginID = HttpContext.Session.GetInt32("loginID");
            var businesses = _context.businesses
           .Where(b => b.ID == loginID)
           .ToList();
            var service = _context.Services
           .Where(b => b.business_ID == loginID)
           .ToList();

            ViewData["servicename"] = new SelectList(service, "service_name", "service_name");

            ViewData["business_ID"] = new SelectList(businesses, "ID", "name");

            ViewData["Orderstatus_ID"] = new SelectList(orderstatus, "ID", "status_name", reserve.status);

            ViewData["pet_name"] = new SelectList(pets, "name", "name");

            
            //ViewData["business_ID"] = new SelectList(_context.businesses, "ID", "name", reserve.business_ID);
            //ViewData["keeper_id"] = new SelectList(_context.keepers, "ID", "address", reserve.keeper_id);
            ViewData["keeper_id"] = new SelectList(keeper, "ID", "name");
            return View(reserve);
        }

        // POST: Reserves/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,keeper_id,pet_name,business_ID,time,service_name,created_at,status")] Reserve reserve)
        {
            if (id != reserve.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(reserve);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ReserveExists(reserve.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            
            var pets = _context.pets

Tailstale/Controllers/ReservesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Tailstale.Models;

namespace Tailstale.Controllers
{
    public class ReservesController : Controller
    {
        private readonly TailstaleContext _context;

        public ReservesController(TailstaleContext context)
        {
            _context = context;
        }

        // GET: Reserves
        public async Task<IActionResult> Index()
        {
            var tailstaleContext = _context.Reserves.Include(r => r.business).Include(r => r.keeper);
            return View(await tailstaleContext.ToListAsync());
        }

        // GET: Reserves/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reserve = await _context.Reserves
                .Include(r => r.business)
                .Include(r => r.keeper)
                .FirstOrDefaultAsync(m => m.id == id);
            if (reserve == null)
            {
                return NotFound();
            }

            return View(reserve);
        }

        // GET: Reserves/Create
        public IActionResult Create()
        {
            ViewData["business_ID"] = new SelectList(_context.businesses, "ID", "name");
            ViewData["keeper_id"] = new SelectList(_context.keepers, "ID", "address");
            return View();
        }

        // POST: Reserves/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,keeper_id,pet_name,business_ID,time,service_name,created_at")] Reserve reserve)
        {
            if (ModelState.IsValid)
            {
                _context.Add(reserve);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["business_ID"] = new SelectList(_context.businesses, "ID", "name", reserve.business_ID);
            ViewData["keeper_id"] = new SelectList(_context.keepers, "ID", "address", reserve.keeper_id);
            return View(reserve);
        }

        // GET: Reserves/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reserve = await _context.Reserves.FindAsync(id);
            if (reserve == null)
            {
                return NotFound();
            }
            ViewData["business_ID"] = new SelectList(_context.businesses, "ID", "name", reserve.business_ID);
            ViewData["keeper_id"] = new SelectList(_context.keepers, "ID", "address", reserve.keeper_id);
            return View(reserve);
        }

        // POST: Reserves/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,keeper_id,pet_name,business_ID,time,service_name,created_at")] Reserve reserve)
        {
            if (id != reserve.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(reserve);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ReserveExists(reserve.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["business_ID"] = new SelectList(_context.businesses, "ID", "name", reserve.business_ID);
            ViewData["keeper_id"] = new SelectList(_context.keepers, "ID", "address", reserve.keeper_id);
            return View(reserve);
        }

        // GET: Reserves/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reserve = await _context.Reserves
                .Include(r => r.business)
                .Include(r => r.keeper)
                .FirstOrDefaultAsync(m => m.id == id);
            if (reserve == null)
            {
                return NotFound();
            }

            return View(reserve);
        }

        // POST: Reserves/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var reserve = await _context.Reserves.FindAsync(id);
            if (reserve != null)
            {
                _context.Reserves.Remove(reserve);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ReserveExists(int id)
        {
            return _context.Reserves.Any(e => e.id == id);
        }
    }
}

Tailstale/Views/Reserve/Delete.cshtml
@model Tailstale.Models.Reserve

@{
    ViewData["Title"] = "Delete";
}
@section Styles {
    <link href="~/css/sshowdelete.css" rel="stylesheet" />
}
<div class="container">
<h1>刪除預約紀錄</h1>

<h3>您確定是否刪除此筆預約紀錄?</h3>
<div>
    <h4>Reserve</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.pet_name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.pet_name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.time)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.time)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.service_name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.service_name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.created_at)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.created_at)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.business)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.business.name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.keeper)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.keeper.name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.status)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.statusNavigation.status_name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="id" />
        <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
            刪除
        </button>|
        <a class="btn btn-secondary" asp-action="Index">返回</a>

        <!-- Modal -->
        <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="staticBackdropLabel">刪除預約紀錄</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        請問確定是否要刪除此筆預約紀錄
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">取消</button>
                        <input type="submit" value="刪除" class="btn btn-danger" />
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
</div>

Tailstale/Views/Reserve/Details.cshtml
@model Tailstale.Models.Reserve

@{
    ViewData["Title"] = "Details";
}
@section Styles {
    <link href="~/css/sshowdelete.css" rel="stylesheet" />
}

<div class="container">
<h1>顯示預約紀錄</h1>


<div>
    @* <h4>Reserve</h4> *@
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.pet_name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.pet_name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.time)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.time)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.service_name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.service_name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.created_at)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.created_at)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.business)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.business.name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.keeper)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.keeper.name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.status)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.statusNavigation.status_name)
        </dd>
    </dl>
</div>
<div>
    <a class="btn btn-success" asp-action="Edit" asp-route-id="@Model?.id">修改</a> |
    <a class="btn btn-secondary" asp-action="Index">返回</a>
</div>
</div>

Tailstale/Views/Reserve/Edit.cshtml
@model Tailstale.Models.Reserve

@{
    ViewData["Title"] = "Edit";
}
@section Styles {
    <link href="~/css/salonfrom.css" rel="stylesheet" />
}
<div class="container">
<h1>修改預約紀錄</h1>

@* <h4>Reserve</h4> *@
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="id" />
            <div class="form-group">
                <label asp-for="keeper_id" class="control-label"></label>
                <select asp-for="keeper_id" class="form-control" asp-items="ViewBag.keeper_id"></select>
                <span asp-validation-for="keeper_id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="pet_name" class="control-label"></label>
               @*  <input asp-for="pet_name" class="form-control" /> *@
                <select asp-for="pet_name" class="form-control" asp-items="ViewBag.pet_name"></select>
                <span asp-validation-for="pet_name" class="text-danger"></span>
                
            </div>
            <div class="form-group">
                <label asp-for="business_ID" class="control-label"></label>
                <select asp-for="business_ID" class="form-control" asp-items="ViewBag.business_ID"></select>
                <span asp-validation-for="business_ID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="time" class="control-label"></label>
                <input asp-for="time" class="form-control" />
                <span asp-validation-for="time" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="service_name" class="control-label"></label>
                <select asp-for="service_name" class="form-control" asp-items="ViewBag.servicename"></select>
                <span asp-validation-for="service_name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="created_at" class="control-label"></label>
                <input asp-for="created_at" class="form-control" readonly />
                <span asp-validation-for="created_at" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="status" class="control-label"></label>
                <select asp-for="status" class="form-control" asp-items="ViewBag.Orderstatus_ID"></select>
                <span asp-validation-for="status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-secondary mt-3" asp-action="Index">返回</a>
</div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Tailstale/Views/Reserve/Index.cshtml
@model IEnumerable<Tailstale.Models.Reserve>

@{
    ViewData["Title"] = "Index";
}
@section Styles {
    <style>
        td {
            max-width: 300px; /* 设置最大宽度 */
            overflow: hidden; /* 隐藏超出部分 */
            text-overflow: ellipsis; /* 使用省略号表示更多内容 */
            white-space: nowrap; /* 强制文本在同一行显示 */
        }

        table {
            border-collapse: collapse;
            width: 100%;
            border-radius: 5px;
        }

        th, td {
            border: 2px solid #dddddd;
            text-align: left;
            padding: 8px;
        }

        .bi {
            font-size: 22px;
        }

        
        .mybtn {
            background-color: #fa2;
        }
    
    </style>
}
@* <header>
    <partial name="_NavBar" />
</header> *@
<div class="container">
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"> <a asp-area="" asp-controller="Salon" asp-action="Settings">美容設定</a></li>
        <li class="breadcrumb-item active" aria-current="page">預約紀錄</li>
    </ol>
</nav>
<h1>預約紀錄</h1>

<p>
    <a class="btn mybtn" asp-action="Create"><i class="bi bi-hand-index-thumb"></i>新增預約</a>
</p>
<div>
    <h3><i class="bi bi-search"></i>依據日期查詢預約</h3>
    
    <input type="date" class="form-control" id="time" name="time" value="" />
    <input id="selectday" type="submit" value="查詢" class="btn mybtn mt-2" />
    <div class="mb-3">
        <div id="orders">
            <table class="table border table-striped">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.pet_name)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.time)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.service_name)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.created_at)
                        </th>
                        <th>
                            門市
                            @* @Html.DisplayNameFor(model => model.business) *@
                        </th>
                        <th>
                            會員
                            @* @Html.DisplayNameFor(model => model.keeper) *@
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.status)
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.pet_name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.time)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.service_name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.created_at)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.business.name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.keeper.ID)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.statusNavigation.status_name)
                            </td>
                            <td>
                                <a asp-action="Edit" asp-route-id="@item.id"><i class="bi bi-highlighter"></i></a> |
                                <a asp-action="Details" asp-route-id="@item.id"><i class="bi bi-info-circle"></i></a> |
                                <a asp-action="Delete" asp-route-id="@item.id"><i class="bi bi-trash-fill"></i></a>
                                <a asp-action="Create" asp-controller="Consumption_Record"
                                   asp-route-keeper_id="@item.keeper_id"
                                   asp-route-pet_name="@item.pet_name"
                                   asp-route-business_ID="@item.business_ID"
                                   asp-route-time="@item.time.ToString("yyyy-MM-ddTHH:mm")"
                                   asp-route-service_name="@item.service_name"
                                   class="btn btn-primary">消費紀錄</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>

        </div>@*局部顯示會在這裡*@
    </div>
</div>
</div>

@section Scripts
{
    <script>
        function updateOrders() { //查詢要發送ajax呼叫,不會刷新
         
            var selectedDate = document.getElementById("time").value;
            $.ajax({ //ajax呼叫需要接物件當參數,物件用{},物件要填屬性

                type: "post",//動詞get
                //url:`/Customers/Orders/${CustomerId.value}`,//``可以把變數帶進去, 這段這樣寫發行會有問題,這只能在vs用
                url: `@Url.Action("Index", "Reserve")`, //這是發行後可以網址正常,Url是urlhelper,負責生成網址列?的內容,這段是server端語法
                data: { 
                    time: selectedDate },
            }).done(data => {  //成功要做啥,收到結果,如果收到data要拿來做甚麼用,後端送回來的data是html(因為是IActionResult),
                $("#orders").html(data);//抓到orders把它整個內容(html)換掉換成data
            }).fail(err => { //呼叫錯誤要做啥,收到error要拿來做啥
                console.log(err.responseText);//他就給你error而已?,也可以用.statusCode狀態瑪?,或用status
            });
        }

        $("#selectday").on("click", function () {//偵測下拉選項的選項如果改變,
            //alert(CustomerId.value);  秀出她的value,這樣就可以查到下拉選項隱藏的內容,我只要拿這個CustomerId(我們想做關聯查詢的那個紀錄)欄位資料發送呼叫到server端撈出這個客戶的訂單就可以了

            updateOrders();//使用此函

        });

    </script>
}