Tailstale/Controllers/vet_informationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Policy;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Templates.BlazorIdentity.Pages;
using Tailstale.Filter;
using Tailstale.Hospital_ViewModel;
using Tailstale.Models;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace Tailstale.Controllers
{
    [IsHospitalFilter]
    public class vet_informationController : Controller
    {
        private readonly TailstaleContext _context;

        public vet_informationController(TailstaleContext context)
        {
            _context = context;            
        }

        // GET: vet_information
        public async Task<IActionResult> Index()
        {
            int LoginID= (int)HttpContext.Session.GetInt32("loginID");
            try
            {
                //var tailstaleContext = _context.vet_informations.Include(v => v.business).Include(v => v.department);

                var v_Infovm = from v_info in _context.vet_informations
                               join b_img in _context.business_imgs
                               on v_info.business_img_ID equals b_img.ID                               
                               where v_info.business_ID == LoginID
                               orderby v_info.employment_status descending
                               select new vet_information_ViewModel
                               {
                                   vet_ID = v_info.vet_ID,
                                   vet_name = v_info.vet_name,
                                   license_number = v_info.license_number,
                                   profile = v_info.profile,
                                   business_ID = v_info.business_ID,
                                   business = v_info.business,
                                   department_ID = v_info.department_ID,
                                   department = v_info.department,
                                   business_img_ID = b_img.ID,
                                   business_img= b_img,
                                   URL = b_img.URL,
                                   name = b_img.name,
                                   employment_status= (bool)v_info.employment_status,
                               };

                return View(v_Infovm);
            }
            catch (Exception ex)
            {
                // 記錄錯誤訊息
                // Log.Error(ex, "An error occurred while executing Index.");
                return StatusCode(500, "Internal server error: " + ex.Message);
            }
        }

        // GET: vet_information/Details/5
        public async Task<IActionResult> Details(int? id)
        {            
            if (id == null)
            {
                return NotFound();
            }
            
            var v_Infovm = await (from v_info in _context.vet_informations
                                  join b_img in _context.business_imgs
                                  on v_info.business_img_ID equals b_img.ID
                                  join b_img_types in _context.business_img_types
                                  on b_img.img_type_id equals b_img_types.ID
                                  where v_info.vet_ID == id
                                  select new vet_information_ViewModel
                                  {
                                      vet_ID = v_info.vet_ID,
                                      vet_name = v_info.vet_name,
                                      license_number = v_info.license_number,
                                      profile = v_info.profile,
                                      business_ID = v_info.business_ID,
                                      business = v_info.business,
                                      department_ID = v_info.department_ID,
                                      department = v_info.department,
                                      business_img_ID = b_img.ID,
                                      business_img = b_img,
                                      URL = b_img.URL,
                                      name = b_img.name,
                                      employment_status= (bool)v_info.employment_status,
                                  }).FirstOrDefaultAsync();

            return View(v_Infovm);
        }

        // GET: vet_information/Createwq
        public IActionResult Create(int id)
        {
            int LoginID = (int)HttpContext.Session.GetInt32("loginID");
            id = LoginID;
            ViewData["business_ID"] = new SelectList(_context.businesses.Where(b => b.ID == LoginID), "ID", "name");
            ViewData["department_ID"] = new SelectList(_context.departments.Where(d=>d.business_ID==id), "department_ID", "department_name");
            return View();
        }


        // POST: vet_information/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(insert_vet_information_ViewModel v_Infovm)
        {
            int LoginID = (int)HttpContext.Session.GetInt32("loginID");
            if (ModelState.IsValid)
            {                
                // 判斷是否有上傳檔案
                if (Request.Form.Files["URL"] != null)
                {
                    // 取得照片欄位名稱
                    var pictureFile = Request.Form.Files["URL"];

                    // 新增存圖檔路徑
                    var uploadsFolder = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/lib/HospitalImages");
                    // 確保目標目錄存在
                    if (!Directory.Exists(uploadsFolder))
                    {
                        // 如果路徑不在則創建
                        Directory.CreateDirectory(uploadsFolder);
                    }

                    // 生成唯一的文件名以避免重名
                    var uniqueFileName = Guid.NewGuid().ToString() + "_" + pictureFile.FileName;

                    // 目標文件的完整路徑
                    var filePath = Path.Combine(uploadsFolder, uniqueFileName);

                    // 將文件保存到指定路徑
                    using (var fileStream = new FileStream(filePath, FileMode.Create))
                    {
                        await pictureFile.CopyToAsync(fileStream);
                    }
                    // 更新圖片路徑
                    v_Infovm.URL = uniqueFileName;
                    //v_Infovm.name = uniqueFileName;
                }
                business_img_type business_Img_Type = new business_img_type
                {
                    FK_business_id= LoginID,
                    typename="醫師個人照"
                };
                _context.Add(business_Img_Type);
                await _context.SaveChangesAsync();

                business_img business_Img = new business_img
                {
                    URL = v_Infovm.URL,                    
                    name = v_Infovm.URL,
                    img_type_id = business_Img_Type.ID,
                };
                _context.Add(business_Img);
                await _context.SaveChangesAsync();

                vet_information vet_Information = new vet_information
                {
                    vet_name = v_Infovm.vet_name,
                    business_ID = LoginID,
                    license_number = v_Infovm.license_number,
                    department_ID = v_Infovm.department_ID,
                    profile = v_Infovm.profile,
                    business_img_ID = business_Img.ID,                    
                    employment_status=v_Infovm.employment_status,
                };
                _context.Add(vet_Information);
                await _context.SaveChangesAsync();
            }
            else
            {
                return View(v_Infovm);
            }
            ViewData["business_ID"] = LoginID.ToString();
            ViewData["department_ID"] = new SelectList(_context.departments, "department_ID", "department_name", v_Infovm.department_ID);
            return RedirectToAction(nameof(Index));
        }

        // GET: vet_information/Edit
        public async Task<IActionResult> Edit(int id)
        {
            int LoginID = (int)HttpContext.Session.GetInt32("loginID");
            if (id == null)
            {
                return NotFound();
            }
            var v_Infovm = await(from v_info in _context.vet_informations
                           join b_img in _context.business_imgs
                           on v_info.business_img_ID equals b_img.ID                           
                           where v_info.vet_ID== id
                           select new vet_information_ViewModel
                           {
                               vet_ID = v_info.vet_ID,
                               vet_name = v_info.vet_name,
                               license_number = v_info.license_number,
                               profile = v_info.profile,
                               business_ID = LoginID,
                               business = v_info.business,
                               department_ID = v_info.department_ID,
                               department = v_info.department,
                               business_img_ID = b_img.ID,
                               business_img = b_img,
                               URL = b_img.URL,
                               name = b_img.name,
                               employment_status=(bool)v_info.employment_status,
                           }).FirstOrDefaultAsync();

            ViewData["business_ID"] = LoginID.ToString();

Tailstale/Views/vet_information/Create.cshtml
@using Tailstale.Hospital_ViewModel
@model insert_vet_information_ViewModel

@{
    ViewData["Title"] = "Create";
}

@section Styles
{
    
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    
    <style>
        textarea {
            height: 200px;
            width: 100%;
        }
    </style> 
}




<div class="col-12 col-lg-8 offset-lg-2 mt-5">
    <h3>新增醫師</h3>
    <hr>
    <div class="border border-1 border-secondary rounded px-4 py-2 mb-5">
        <div class="container my-4">
            <div class="row">
                <div class="col-12">
                    <form asp-action="Create" enctype="multipart/form-data">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        @* <div class="form-group mb-2">
                            <label asp-for="business_ID" class="control-label"></label>
                            <input asp-for="business_ID" class="form-control" asp-items="ViewBag.business_ID" readonly >
                        </div> *@
                        <div class="form-group mb-2">
                            <label asp-for="vet_name" class="control-label"></label>
                            <input asp-for="vet_name" class="form-control" autocomplete="off"/>
                            <span asp-validation-for="vet_name" class="text-danger"></span>
                        </div>              
                        <div class="form-group mb-2">
                            <label asp-for="license_number" class="control-label"></label>
                            <input asp-for="license_number" class="form-control" autocomplete="off" />
                            <span asp-validation-for="license_number" class="text-danger"></span>
                        </div>
                        <div class="form-group mb-2">
                            <label asp-for="department_ID" class="control-label"></label>
                            <select asp-for="department_ID" class="form-control" asp-items="ViewBag.department_ID">
                                <option selected>===選擇科別===</option>
                            </select>
                        </div>
                        <div class="form-group mb-2">
                            <label asp-for="profile" class="control-label"></label>
                            <textarea asp-for="profile" class="form-control" style="height:200px;width: 100%;"></textarea>
                            <span asp-validation-for="profile" class="text-danger"></span>
                        </div>
                        <div class="form-group form-check mb-2">
                            <label class="form-check-label">
                                <input class="form-check-input" asp-for="employment_status" />在職
                            </label>
                        </div>
                        <div class="form-group mb-2">
                            <div class="row">
                                <div class="col-6">
                                    <label asp-for="URL" class="control-label"></label>
                                    <input asp-for="URL" type="file" accept="image/*" class="form-control" />
                                    <span asp-validation-for="URL" class="text-danger"></span>
                                </div>                            
                            </div>
                        </div>
                                              
                        <div class="form-group mt-5 text-end">      
                            <input id="submit" type="submit" value="新增" class="btn btn-outline-primary" />
                            <a asp-action="Index" class="btn btn-outline-primary">返回醫師列表</a>
                        </div>
                    </form>
                 </div>
            </div>
        </div>
    </div>
</div>

@section Scripts 
{
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>

    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script>
        $(document).ready(function () {
            $('#URL').on("change", function () {
                // 允許的副檔名
                var allowType = "image.*";
                // 上傳的第一個檔案
                var file = this.files[0];
                // 抓取檔案的型態是否為allowType的格式
                if (file.type.match(allowType)) {
                    // 讀取圖片
                    var reader = new FileReader();
                    // 檔案讀取完成的事件
                    reader.onload = function (e) {
                        // 選到#Picture的上一個元素修改src屬性
                        $('#URL').prev().attr("src", e.target.result);
                        // 選到#Picture的上一個元素修改title屬性
                        $('#URL').prev().attr("title", e.file.name);
                    }
                    // 用圖片的URL讀取圖片
                    reader.readAsDataURL(file);
                    // 解除鎖定按鈕
                    $('.btn').prop("disabled", false);
                } else {
                    alert("不支援的檔案上傳類型");
                    // 鎖定按鈕
                    $('.btn').prop("disabled", true);
                }
            });

        });

    </script>
}

Tailstale/Views/vet_information/Delete.cshtml
@using Tailstale.Hospital_ViewModel
@model vet_information_ViewModel

@{
    ViewData["Title"] = "Delete";
}

@section Styles
{

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">

    <style>
        textarea {
            height: 200px;
            width:100%;
        }
    </style>
}


<h4>確認要刪除此筆醫師資料嗎?</h4>
<hr />

<div class="row">
    <div class="col-12 col-md-8 offset-md-2 ">
        <div class="border border-1 border-secondary rounded px-4 py-2">
            <div class="container mt-4">
                <div class="row">
                    <div class="col-12 col-md-6">
                        <dl>
                            <dd class="text-center">
                                <partial name="_showimgPartial">
                            </dd>
                        </dl>
                    </div>
                    <div class="col-12 col-md-6">
                        <dl>
                            <dt>
                                @Html.DisplayNameFor(model => model.business)
                            </dt>
                            <dd>
                                @Html.DisplayFor(model => model.business.name)
                            </dd>
                            <dt>
                                @Html.DisplayNameFor(model => model.department)
                            </dt>
                            <dd>
                                @Html.DisplayFor(model => model.department.department_name)
                            </dd>
                            <dt>
                                @Html.DisplayNameFor(model => model.vet_name)
                            </dt>
                            <dd>
                                @Html.DisplayFor(model => model.vet_name)
                            </dd>
                            <dt>
                                @Html.DisplayNameFor(model => model.license_number)
                            </dt>
                            <dd>
                                @Html.DisplayFor(model => model.license_number)
                            </dd>
                        </dl>
                    </div>
                </div>
            </div>
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <dl>
                            <dt class="">
                                @Html.DisplayNameFor(model => model.profile)
                            </dt>
                            <dd class="">
                                <textarea readonly>
                                    @Html.DisplayFor(model => model.profile)
                                </textarea>
                            </dd>
                            <div class="text-end mt-3">
                                <form asp-action="Delete">
                                    <input type="hidden" asp-for="vet_ID" />
                                    <input type="submit" value="確認刪除" class="btn btn-outline-danger" id="delete_vet" />
                                    <a asp-action="Index" class="btn btn-outline-primary">返回醫師列表</a>
                                </form>
                            </div>
                        </dl>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>



@section Scripts
{
   @*  <script>
        $(document).ready(function () {
            $('#delete_vet').on('click', function () {
                if (confirm('確定要刪除此筆資料嗎?')) {
                    // 使用者點擊確定
                    // 在這裡添加刪除資料的邏輯
                    console.log('資料已刪除');
                } else {
                    // 使用者點擊取消
                    console.log('刪除操作已取消');
                }
            });
        });

    </script> *@
}

Tailstale/Views/vet_information/Details.cshtml
@* @model vet_information_ViewModel

@{
    ViewData["Title"] = "Details";
}

@section Styles
{
   
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    
    <style>
        textarea {
            height: 200px;
            width: 100%;
        }
    </style>
}

<h2>檢視醫師資料</h2>
<hr />
<div class="row">
    <div class="col-12 col-md-8 offset-md-2 ">
        <div class="border border-1 border-secondary rounded px-4 py-2">
            <div class="container mt-4">
                <div class="row">
                    <div class="col-12 col-md-6">
                        <dl>
                            <dd class="text-center">
                                <partial name="_showimgPartial">
                            </dd>
                        </dl>
                    </div>
                    <div class="col-12 col-md-6">
                        <dl>
                            <dt>
                                @Html.DisplayNameFor(model => model.business)
                            </dt>
                            <dd>
                                @Html.DisplayFor(model => model.business.name)
                            </dd>
                            <dt>
                                @Html.DisplayNameFor(model => model.department)
                            </dt>
                            <dd>
                                @Html.DisplayFor(model => model.department.department_name)
                            </dd>
                            <dt>
                                @Html.DisplayNameFor(model => model.vet_name)
                            </dt>
                            <dd>
                                @Html.DisplayFor(model => model.vet_name)
                            </dd>
                            <dt>
                                @Html.DisplayNameFor(model => model.license_number)
                            </dt>
                            <dd>
                                @Html.DisplayFor(model => model.license_number)
                            </dd>
                        </dl>
                    </div>
                </div>
            </div>
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <dl>
                            <dt class="">
                                @Html.DisplayNameFor(model => model.profile)
                            </dt>
                            <dd>
                                <pre style="height:200px;width:100%" class="border border-1 border-secondary" readonly>
                                    @Html.DisplayFor(model => model.profile)
                                </pre>
                            </dd>
                            <div class="text-end mt-3">
                                <a asp-action="Edit" asp-route-id="@Model?.vet_ID" class="btn btn-outline-primary">修改資料</a>
                                <a asp-action="Index" class="btn btn-outline-primary">返回醫師列表</a>
                            </div>
                        </dl>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts
{
 <script>
     $(document).ready(function () {

     });

 </script>
} *@

Tailstale/Views/vet_information/Index.cshtml
@model IEnumerable<Tailstale.Hospital_ViewModel.vet_information_ViewModel>


@{
    ViewData["Title"] = "Index";
}

@section Styles
{    
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link href="https://cdn.datatables.net/2.1.3/css/dataTables.bootstrap5.css" rel="stylesheet" />
}


<div class="container mt-5">
    <div class="row">   
        <h3>醫師資訊管理</h3>
        <hr>
        <div class="list-group col-2 text-start">
            <a asp-action="Index" asp-controller="Appointments" class="list-group-item list-group-item-action sidebar-item">預約記錄管理</a>
            <a asp-action="Details" asp-controller="Appointments" class="list-group-item list-group-item-action sidebar-item">過去預約記錄檢視</a>
            <a asp-action="Index" asp-controller="daily_outpatient_clinic_schedule" class="list-group-item list-group-item-action sidebar-item">門診表管理</a>
            <a asp-action="Index" asp-controller="outpatient_clinic" class="list-group-item list-group-item-action sidebar-item ">門診資訊管理</a>
            <a asp-action="Index" asp-controller="departments" class="list-group-item list-group-item-action sidebar-item">科別管理</a>
            <a asp-action="Index" asp-controller="vet_information" class="list-group-item list-group-item-action sidebar-item active">醫師資訊管理</a>
            <a asp-action="Index" asp-controller="ward" class="list-group-item list-group-item-action sidebar-item">院內病房管理</a>
            <a href="#" class="list-group-item list-group-item-action sidebar-item">Option 6</a>
            <a href="#" class="list-group-item list-group-item-action sidebar-item">Option 7</a>
            <a href="#" class="list-group-item list-group-item-action sidebar-item">Option 8</a>
            <a href="#" class="list-group-item list-group-item-action sidebar-item">Option 9</a>
            <a href="#" class="list-group-item list-group-item-action sidebar-item">Option 10</a>
        </div>
       
        <div class="col-10">           
            <div class="mb-2">
                <a asp-action="Create" class="btn btn-outline-primary"><i class="bi bi-plus-lg"></i> 新增醫師</a>
            </div>
            <table class="table">
                <thead>
                    <tr>
                        
                        <th>
                            @Html.DisplayNameFor(model => model.department)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.vet_name)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.license_number)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.employment_status)
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            
                            <td>
                                @Html.DisplayFor(modelItem => item.department.department_name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.vet_name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.license_number)
                            </td>
                            <td>
                                @if (item.employment_status == true)
                                {
                                    <p>在職</p>
                                }
                                else
                                {
                                    <p>離職</p>
                                }
                            </td>
                            <td>
                                <div class="text-end">
                                    <a asp-action="Edit" asp-route-id="@item.vet_ID" class="btn btn-outline-secondary me-1">修改醫師資訊</a>
                                    <a asp-action="Details" asp-route-id="@item.vet_ID" class="btn btn-outline-primary me-1" data-bs-toggle="modal" data-bs-target="#vetDetail-@item.vet_ID">詳細資訊</a>
                                    @* <a asp-action="Delete" asp-route-id="@item.vet_ID" class="btn btn-outline-danger"><i class="bi bi-trash3"></i></a> *@
                                </div>
                            </td>
                        </tr>

                        <!-- vetInfo_Modal Start-->
                        <div class="modal fade" id="vetDetail-@item.vet_ID" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                            <div class="modal-dialog modal-lg">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="">醫師個人資訊</h5>
                                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                    </div>
                                    <div class="modal-body">
                                        <partial name="_vetDetail_Partial" model="@item">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- vetInfo_Modal End-->
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

@section Scripts
{
    <script src="https://cdn.datatables.net/2.1.3/js/dataTables.js"></script>
    <script src="https://cdn.datatables.net/2.1.3/js/dataTables.bootstrap5.js"></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/fixedheader/3.2.1/js/dataTables.fixedHeader.js"></script>
    <script>
        $(document).ready(function () {
            $('.table').DataTable({
                paging: true,
                pageLength: 10, // 每頁顯示的資料筆數
                lengthChange: false, // 隱藏 "顯示多少筆資料" 選項
                searching: true, // 啟用搜尋欄位
                ordering: true, // 啟用排序功能
                info: false, // 隱藏 "顯示第幾頁到第幾頁的資料" 資訊
                autoWidth: false, // 自動調整寬度
                language: {
                    search: "搜尋:",
                    paginate: {
                        first: "第一頁",
                        last: "最後一頁",
                        next: "下一頁",
                        previous: "上一頁"
                    },
                    zeroRecords: "沒有找到符合條件的資料",
                    emptyTable: "表格中沒有數據"
                }
            });
        })
    </script>
}

Tailstale/Views/vet_information/_showimgPartial.cshtml
@using Tailstale.Hospital_ViewModel
@model vet_information_ViewModel

@if (Model.URL == null)
{
    <img id="vet_photo" src="~/imgs/noimage.jpg" title="尚無照片" style="width:360px;height:360px" />
}
else
{
    <img id="vet_photo" src="~/lib/HospitalImages/@Html.DisplayFor(model => model.URL)" title="@Html.DisplayFor(model => model.name)" style="width:360px;height:360px" />
}