Tailstale/Controllers/Sbusiness_imgController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Policy;
using System.Threading.Tasks;
using CRUD_COREMVC;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Templates.BlazorIdentity.Pages;
using Tailstale.Models;

namespace Tailstale.Controllers
{
    [IsLoginFilter]
    public class Sbusiness_imgController : Controller
    {
        private readonly TailstaleContext _context;
        private readonly IWebHostEnvironment _hostingEnvironment;

        public Sbusiness_imgController(TailstaleContext context, IWebHostEnvironment hostingEnvironment)
        {
            _context = context;
            _hostingEnvironment = hostingEnvironment;
        }

        // GET: business_img
        public async Task<IActionResult> Index()
        {
            int? loginID = HttpContext.Session.GetInt32("loginID");
            int? loginType = HttpContext.Session.GetInt32("loginType");
            var business_img_type = await _context.business_img_types
           .Where(b => b.FK_business_id == loginID)
           .ToListAsync();
            ViewData["img_type"] = new SelectList(business_img_type, "ID", "typename");
            return View();
        }



        [HttpPost]
        public async Task<IActionResult> Index(int? id)
        {



            // 準備查詢
            IQueryable<business_img> query = _context.business_imgs
                .Include(bh => bh.img_type)
                 .OrderByDescending(bh => bh.ID);


            // 根據 id 的情況添加條件
            if (id.HasValue)
            {
                query = query.Where(bh => bh.img_type_id == id);
            }



            // 执行查询并返回结果
            var S_img_type = await query.ToListAsync();

            return PartialView("_Sbusiness_imgPartial", S_img_type);


        }








        // GET: business_img/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var business_img = await _context.business_imgs
                .Include(b => b.img_type)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (business_img == null)
            {
                return NotFound();
            }

            return View(business_img);
        }

        // GET: business_img/Create
        public IActionResult Create()
        {
            int? loginID = HttpContext.Session.GetInt32("loginID");
            var query = from business in _context.businesses
                        join imgType in _context.business_img_types
                        on business.ID equals imgType.FK_business_id
                        where business.ID == loginID
                        select new
                        {
                            ImageTypeID = imgType.ID,
                            ImageTypeName = imgType.typename
                        };

            var result =  query.ToList();

            ViewData["ImageTypeList"] = new SelectList(result, "ImageTypeID", "ImageTypeName");
            ViewData["img_type_id"] = new SelectList(_context.business_img_types, "ID", "typename");
            return View();
        }

        // POST: business_img/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,img_type_id,URL,name,created_at")] Sbusiness_imgViewModel business_img)
        {
            if (ModelState.IsValid)
            {
                if (HttpContext.Request.Form.Files.Count > 0) // 检查是否有文件上传
                {
                    var photoFile = HttpContext.Request.Form.Files[0]; // 获取第一个上传的文件

                    if (photoFile != null && photoFile.Length > 0) // 检查文件是否有效
                    {
                        // 生成唯一的文件名，避免重复
                        string uniqueFileName = Guid.NewGuid().ToString() + "_" + Path.GetFileName(photoFile.FileName);

                        // 指定文件的完整路径，将文件保存到 wwwroot/images 文件夹下
                        string filePath = Path.Combine(_hostingEnvironment.WebRootPath, "Salon_img", uniqueFileName);


                        using (var stream = new FileStream(filePath, FileMode.Create))
                        {
                            await photoFile.CopyToAsync(stream); // 将文件复制到指定路径
                        }

                        // 将文件名（包含扩展名）保存到 service 对象的 service_img 属性
                        business_img.URL = uniqueFileName;
                    }
                }
                business_img a = new business_img()
                {
                    img_type_id = business_img.img_type_id,
                    URL = business_img.URL,
                    name = business_img.name,
                };
                // 将 service 对象添加到数据库上下文并保存更改
                _context.Add(a);
                await _context.SaveChangesAsync();

                // 成功保存后重定向到 Index 页面
                return RedirectToAction(nameof(Index));
            }
            int? loginID = HttpContext.Session.GetInt32("loginID");
            var query = from business in _context.businesses
                        join imgType in _context.business_img_types
                        on business.ID equals imgType.FK_business_id
                        where business.ID == loginID
                        select new
                        {
                            ImageTypeID = imgType.ID,
                            ImageTypeName = imgType.typename
                        };

            var result = query.ToList();

            ViewData["ImageTypeList"] = new SelectList(result, "ImageTypeID", "ImageTypeName");


            //ViewData["img_type_id"] = new SelectList(_context.business_img_types, "ID", "ID", business_img.img_type_id);
            ViewData["img_type_id"] = new SelectList(_context.business_img_types, "ID", "typename", business_img.img_type_id);//預設選到我傳進來的這參數他的img_type_id
            return View(business_img);
        }

        // GET: business_img/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var business_img = await _context.business_imgs.FindAsync(id);
            if (business_img == null)
            {
                return NotFound();
            }
            int? loginID = HttpContext.Session.GetInt32("loginID");
            var query = from business in _context.businesses
                        join imgType in _context.business_img_types
                        on business.ID equals imgType.FK_business_id
                        where business.ID == loginID
                        select new
                        {
                            ImageTypeID = imgType.ID,
                            ImageTypeName = imgType.typename
                        };

            var result = query.ToList();

            ViewData["ImageTypeList"] = new SelectList(result, "ImageTypeID", "ImageTypeName");

            ViewData["img_type_id"] = new SelectList(_context.business_img_types, "ID", "typename", business_img.img_type_id);
            return View(business_img);
        }

        // POST: business_img/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,img_type_id,URL,name,created_at")] business_img business_img)
        {
            if (id != business_img.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    // 取得原始的 Service 資料
                    var originalService = await _context.business_imgs.AsNoTracking().FirstOrDefaultAsync(s => s.ID == business_img.ID);

                    // 檢查是否有新的圖片文件上傳
                    if (HttpContext.Request.Form.Files.Count > 0)
                    {
                        var photoFile = HttpContext.Request.Form.Files[0]; // 取得第一個上傳的文件

                        if (photoFile != null && photoFile.Length > 0) // 檢查文件有效性
                        {
                            // 生成唯一的文件名，避免重复
                            string uniqueFileName = Guid.NewGuid().ToString() + "_" + Path.GetFileName(photoFile.FileName);

                            // 指定文件的完整路徑，保存到 wwwroot/Salon_img 文件夾下
                            string filePath = Path.Combine(_hostingEnvironment.WebRootPath, "Salon_img", uniqueFileName);

                            // 保存文件到目標路徑
                            using (var stream = new FileStream(filePath, FileMode.Create))
                            {
                                await photoFile.CopyToAsync(stream);
                            }

                            // 刪除舊的檔案
                            DeleteImageFile(originalService.URL);

                            // 更新 service_img 屬性為新的文件名
                            business_img.URL = uniqueFileName;
                        }
                    }
                    else
                    {
                        // 沒有新圖片上傳，保留原有的 service_img 值
                        business_img.URL = originalService.URL;
                    }

                    // 更新 Service 資料
                    _context.Update(business_img);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!business_imgExists(business_img.ID))
                    {
                        return NotFound();

Tailstale/Views/Sbusiness_img/Create.cshtml
@model Tailstale.Models.Sbusiness_imgViewModel

@{
    ViewData["Title"] = "Create";
}
@section Styles {
    <link href="~/css/salonfrom.css" rel="stylesheet" />
}
<div class="container">
<h1>新增作品圖片</h1>

@* <h4>business_img</h4> *@
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="img_type_id" class="control-label">類型名稱</label>
               @*  <select asp-for="img_type_id" class ="form-control" asp-items="ViewBag.img_type_id"></select> *@
                <select asp-for="img_type_id" class="form-control" asp-items="ViewBag.ImageTypeList"></select>
            </div>
            <div class="form-group">
                <label asp-for="URL" class="control-label">圖片</label>
                <input asp-for="URL" class="form-control" type="file" accept="image/*" onchange="previewImage(this)" />
                <span asp-validation-for="URL" class="text-danger"></span>
                <img id="imgPreview" src="~/Salon_img/111.jpg" width="200" height="250" />
            </div>
            <div class="form-group">
                <label asp-for="name" class="control-label">圖片名稱</label>
                <input asp-for="name" class="form-control" placeholder="需加上關鍵字,如貓或狗" required />
                <span asp-validation-for="name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-secondary mt-3" asp-action="Index">返回</a>
</div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

   <script>
        function previewImage(input) {
            var imgPreview = document.getElementById('imgPreview');
            if (input.files && input.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    imgPreview.src = e.target.result;
                }
                reader.readAsDataURL(input.files[0]);
            }
            else {
                imgPreview.src = '@Url.Content("~/Salon_img/111.jpg")'; // 如果没有选择文件，则显示默认图片
            }
        }

        // 使用者選擇不同的檔案時觸發預覽
        document.getElementById('URL').onchange = function () {
            previewImage(this);
        };
   </script>
}

Tailstale/Views/Sbusiness_img/Delete.cshtml
@model Tailstale.Models.business_img

@{
    ViewData["Title"] = "Delete";
}
@section Styles {
    <link href="~/css/sshowdelete.css" rel="stylesheet" />
}
<div class="container">
<h1>刪除作品圖片</h1>

<h3>您確定是否刪除此筆作品圖片?</h3>
<div>
    <h4>business_img</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            圖片
           @*  @Html.DisplayNameFor(model => model.URL) *@
        </dt>
        <dd class = "col-sm-10">
            <img src="~/Salon_img/@Html.DisplayFor(model => model.URL)" alt="Alternate Text" style="width:360px;height:500px" />
        </dd>
        <dt class = "col-sm-2">
            圖片名稱
            @* @Html.DisplayNameFor(model => model.name) *@
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.name)
        </dd>
        <dt class = "col-sm-2">
            建立日期
           @*  @Html.DisplayNameFor(model => model.created_at) *@
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.created_at)
        </dd>
        <dt class = "col-sm-2">
            類型名稱
            @* @Html.DisplayNameFor(model => model.img_type) *@
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.img_type.typename)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
            刪除
        </button>|
        <a class="btn btn-secondary" asp-action="Index">返回</a>

        <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="staticBackdropLabel">刪除作品圖片</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        請問確定是否要刪除此筆作品圖片
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">取消</button>
                        <input type="submit" value="刪除" class="btn btn-danger" />
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
</div>

Tailstale/Views/Sbusiness_img/Details.cshtml
@model Tailstale.Models.business_img

@{
    ViewData["Title"] = "Details";
}
@section Styles {
    <link href="~/css/sshowdelete.css" rel="stylesheet" />
}
<div class="container">
<h1>顯示作品圖片</h1>

<div>
    @* <h4>business_img</h4> *@
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            圖片
            @* @Html.DisplayNameFor(model => model.URL) *@
        </dt>
        <dd class = "col-sm-10">
            <img src="~/Salon_img/@Html.DisplayFor(model => model.URL)" alt="Alternate Text" style="width:360px;height:500px" />
           
        </dd>
        <dt class = "col-sm-2">
            圖片名稱
            @* @Html.DisplayNameFor(model => model.name) *@
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.name)
        </dd>
        <dt class = "col-sm-2">
            建立日期
            @* @Html.DisplayNameFor(model => model.created_at) *@
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.created_at)
        </dd>
        <dt class = "col-sm-2">
            類型名稱
           @*  @Html.DisplayNameFor(model => model.img_type) *@
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.img_type.typename)
        </dd>
    </dl>
</div>
<div>
    <a class="btn btn-success" asp-action="Edit" asp-route-id="@Model?.ID">修改</a> |
    <a class="btn btn-secondary" asp-action="Index">返回</a>
</div>
</div>

Tailstale/Views/Sbusiness_img/Edit.cshtml
@model Tailstale.Models.business_img

@{
    ViewData["Title"] = "Edit";
}
@section Styles {
    <link href="~/css/salonfrom.css" rel="stylesheet" />
}
<div class="container">
<h1>修改作品圖片</h1>

@* <h4>business_img</h4> *@
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="img_type_id" class="control-label">類型名稱</label>
                <select asp-for="img_type_id" class="form-control" asp-items="ViewBag.ImageTypeList"></select>
               @*  <select asp-for="img_type_id" class="form-control" asp-items="ViewBag.img_type_id"></select> *@
                <span asp-validation-for="img_type_id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="URL" class="control-label">圖片</label>
                <input asp-for="URL" class="form-control" type="file" accept="image/*" class="form-control-file" onchange="previewImage(this, 'imgPreviewPhoto')" />
                <span asp-validation-for="URL" class="text-danger"></span>
                    <img id="imgPreviewPhoto" src="~/Salon_img/@(Model.URL ?? "111.jpg")" width="200" height="250" />
            </div>
            <div class="form-group">
                <label asp-for="name" class="control-label">圖片名稱</label>
                <input asp-for="name" class="form-control" required />
                <span asp-validation-for="name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="created_at" class="control-label">建立日期</label>
                <input asp-for="created_at" class="form-control" readonly />
                <span asp-validation-for="created_at" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-secondary mt-3" asp-action="Index">返回</a>
</div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script>
        window.onload = function () {
            var photoInput = document.getElementById('URL');

            photoInput.onchange = function () {
                previewImage(this, 'imgPreviewPhoto', '@Url.Content("~/Salon_img/")', '@Model.URL');
            };

            function previewImage(input, imgId, baseUrl, defaultImage) {
                var imgPreview = document.getElementById(imgId);
                if (input.files && input.files[0]) {
                    var reader = new FileReader();
                    reader.onload = function (e) {
                        imgPreview.src = e.target.result;
                    }
                    reader.readAsDataURL(input.files[0]);
                }
                else {
                    // 如果没有选择文件，则显示默认图片
                    imgPreview.src = baseUrl + defaultImage;
                }
            }
        };
    </script>
}

Tailstale/Views/Sbusiness_img/Index.cshtml
@model IEnumerable<Tailstale.Models.business_img>

@{
    ViewData["Title"] = "Index";
}
@section Styles {
    <style>
        td {
            max-width: 300px; /* 设置最大宽度 */
            overflow: hidden; /* 隐藏超出部分 */
            text-overflow: ellipsis; /* 使用省略号表示更多内容 */
            white-space: nowrap; /* 强制文本在同一行显示 */
        }

        table {
            border-collapse: collapse;
            width: 100%;
            border-radius: 5px;
        }

        th, td {
            border: 2px solid #dddddd;
            text-align: left;
            padding: 8px;
        }

        .bi {
            font-size: 22px;
        }

        
        .mybtn {
            background-color: #fa2;
        }
    
    </style>
}
@* <header>
    <partial name="_NavBar" />
</header> *@
<div class="container">
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"> <a asp-area="" asp-controller="Salon" asp-action="Settings">美容設定</a></li>
        <li class="breadcrumb-item active" aria-current="page">作品上傳</li>
    </ol>
</nav>
<h1>作品圖上傳</h1>

<p>
    <a class="btn mybtn" asp-action="Create"><i class="bi bi-hand-index-thumb"></i>新增作品圖片</a>
</p>


<div>
    <h3><i class="bi bi-search"></i>查詢已上傳美容門市圖片</h3>
    <select id="IdInput" class="form-control" asp-items="ViewBag.img_type"></select>
    <input id="selectday" type="submit" value="查詢" class="btn mybtn mt-2" />
    <div class="mb-3">
        <div id="orders"></div>@*局部顯示會在這裡*@
    </div>
</div>
</div>

@section Scripts
{
    <script>
        function updateOrders() { //查詢要發送ajax呼叫,不會刷新
            var selectedId = document.getElementById("IdInput").value;

            $.ajax({ //ajax呼叫需要接物件當參數,物件用{},物件要填屬性

                type: "post",//動詞get
                //url:`/Customers/Orders/${CustomerId.value}`,//``可以把變數帶進去, 這段這樣寫發行會有問題,這只能在vs用
                url: `@Url.Action("Index", "Sbusiness_img")`, //這是發行後可以網址正常,Url是urlhelper,負責生成網址列?的內容,這段是server端語法
                data: {
                    id: selectedId,

                },
            }).done(data => {  //成功要做啥,收到結果,如果收到data要拿來做甚麼用,後端送回來的data是html(因為是IActionResult),
                $("#orders").html(data);//抓到orders把它整個內容(html)換掉換成data
            }).fail(err => { //呼叫錯誤要做啥,收到error要拿來做啥
                console.log(err.responseText);//他就給你error而已?,也可以用.statusCode狀態瑪?,或用status
            });
        }

        $("#selectday").on("click", function () {//偵測下拉選項的選項如果改變,
            //alert(CustomerId.value);  秀出她的value,這樣就可以查到下拉選項隱藏的內容,我只要拿這個CustomerId(我們想做關聯查詢的那個紀錄)欄位資料發送呼叫到server端撈出這個客戶的訂單就可以了

            updateOrders();//使用此函

        });

    </script>
}

Tailstale/Views/Sbusiness_img/_Sbusiness_imgPartial.cshtml
@model IEnumerable<Tailstale.Models.business_img>


<table class="table border table-striped">
    <thead>
        <tr>
            <th>
                類型名稱
                @* @Html.DisplayNameFor(model => model.img_type) *@
            </th>
            <th>
                圖片
                @* @Html.DisplayNameFor(model => model.URL) *@
            </th>
            <th>
                圖片名稱
                @* @Html.DisplayNameFor(model => model.name) *@
            </th>
            <th>
                建立日期
                @* @Html.DisplayNameFor(model => model.created_at) *@
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
           <td>
                @Html.DisplayFor(modelItem => item.img_type.typename)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.URL)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.created_at)
            </td>
            <td>
                    <a asp-action="Edit" asp-route-id="@item.ID"><i class="bi bi-highlighter"></i></a> |
                    <a asp-action="Details" asp-route-id="@item.ID"><i class="bi bi-info-circle"></i></a> |
                    <a asp-action="Delete" asp-route-id="@item.ID"><i class="bi bi-trash-fill"></i></a>
            </td>
        </tr>
}
    </tbody>
</table>